### ISSUE TITLE
definition of AttrField wrong

### ISSUE THREAD

**Issue by arno-h** [Scotley/vuex-orm-decorators#1]
Hi,

the decorator for AttrField produces a string field. From [attributes.ts, line 46](https://github.com/Scotley/vuex-orm-decorators/blob/d16eeb986ff9cf127c393ab82ed0965621631cb7/src/attributes.ts#L46):

```
export function AttrField(defaultValue?: any) {
    return Field(Model.string(defaultValue));
}
```

I suggest this should be: `Model.attr(defaultValue)`.

best regards,
Arno

**Comment by Scotley** [comment]
Too true.  Good spotting.  I will push the fix in the next couple of days.

Cheers Arno!
