### ISSUE TITLE
Single Table Inheritance

### ISSUE THREAD

**Issue by maartenpaauw** [Scotley/vuex-orm-decorators#10]
I have 2 models; `Setting` and `FooSetting`. According to the docs I setup Single Table Inheritance the following way.

```javascript
import { OrmModel, StringField } from 'vuex-orm-decorators';
import Setting from '@/models/Setting';

@OrmModel('foo-settings', 'settings', {
    FOO: FooSetting,
    GENERAL: Setting,
})
export class FooSetting extends Setting {
    @StringField('')
    test!: string;
}

export default FooSetting;
```

I get the following warning within the console.

```
[Vuex ORM] Model `FooSetting` extends `Setting` which doesn't overwrite Model.types(). You will not be able to use type mapping.
```

Am I implementing this correctly?

**Comment by TiBianMod** [comment]
You implementing this correctly.
In your example the `types` (the 3rd argument on @OrmModel) needs to be register on Setting model in order for the Single Table Inheritance to work.
For the moment the `types` are register on FooSetting model.

I will take a look at it.

**Comment by maartenpaauw** [comment]
It's some time ago, I think I've tried the other way around as well (giving the types to the `Setting` `OrmModel` decorator) but without any luck.

**Comment by TiBianMod** [comment]
Yes i know :(
The only way for the types to work right now is to create a static types method on parent class like the official [vuex-orm example](https://vuex-orm.org/guide/model/single-table-inheritance.html#discriminator-field)


```javascript
export class Setting extends Model {

    static types() {
        return {
            FOO: FooSetting,
            GENERAL: Setting,
        }
    }
    
}
```
