### ISSUE TITLE
Error while compiling on Windows

### ISSUE THREAD

**Issue by JaZo** [Scotley/vuex-orm-decorators#13]
>  ERROR  Failed to compile with 1 errors
>
> This relative module was not found:
>
> * ./model in ./node_modules/vuex-orm-decorators/dist/index.js

The dist folder contains both `Model.js` and `model.js` (and map and ts files also) and this messes up (case insensitive) Windows.

**Comment by TiBianMod** [comment]
Thanks for the report.

Please update to version 1.2.5
