### ISSUE TITLE
Can you add @DateField decorator to determine fields of Date type?

### ISSUE THREAD

**Issue by lxrave** [Scotley/vuex-orm-decorators#14]
It should be work like other decorators, but cast date strings in ISO format to Date object.
I know what I can use {mutate: mutator} param of decorator params, but it is less clearly and less readable )))

**Comment by TiBianMod** [comment]
we definitely need the @DateField decorator :)
I will add the @DateField in the next release (probably this week)

**Comment by lxrave** [comment]
Thank you so much

вт, 22 дек. 2020 г., 01:17 Michalis Giannas <notifications@github.com>:

**Comment by TiBianMod** [comment]
@DateField decorator has been added :)
You can give it a try, is on the next branch or you can installed from  npm is on v2.0.0-beta.3.

I don't know if is working with Vue 2 !!!

**Comment by lxrave** [comment]
I will check it ) Thanks )
