### ISSUE TITLE
The npm-publish started failing

### ISSUE THREAD

**Issue by TiBianMod** [Scotley/vuex-orm-decorators#16]
Hi @Scotley,

the publishing jobs started to fail with the following error..

```console
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/vuex-orm-decorators - Not found
npm ERR! 404 
npm ERR! 404  'vuex-orm-decorators@2.0.0-beta.5' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

* Probably you need to re authenticate the package on `npm` and re run the following [job](https://github.com/Scotley/vuex-orm-decorators/runs/1677300264?check_suite_focus=true) please to make sure is working again.

>* Note: The workflow file is 100% correct, is not there the problem
I have already published 4 releases with this workflow

Please take care of it @Scotley :)

**Comment by Scotley** [comment]
Hi @TiBianMod,

Should be working again now.  NPM decided to jump all my access tokens yesterday, which sucked as I have a tonne of private packages used in CI pipelines which needed updating.  It should work now as I have setup a new token for this repository.

As I no longer use this repository, don't have time to maintain (and you are doing a stellar job) I am happy to hand ownership of this repository to you.

**Comment by TiBianMod** [comment]
Thank you very much @Scotley for the ownership and the quick reply.

> All jobs working again, nice.

I hope you doing well :)

**Comment by TiBianMod** [comment]
Now about the ownership, if you want you can transferred to me (thank you a lot for the trust), personally I will continue maintaining this repo how much I can.

**Comment by Scotley** [comment]
Happy to transfer it, I can see you are transforming the code in a positive way.  Do you have a npmjs account that I can transfer the package across to?

**Comment by TiBianMod** [comment]
I have this account on npm

https://www.npmjs.com/~tibian
and email tibianmod@gmail.com


Thank you very much @Scotley :)

**Comment by TiBianMod** [comment]
The big transformation is happening in the next branch with almost 100% unit test :)

**Comment by TiBianMod** [comment]
Can i change the references about you Name ?

**Comment by Scotley** [comment]
Cool, I have added you as a maintainer and removed myself on npmjs.  No need to reference to me at all, feel free to update anything as you see fit!

Note that you will probably need to change the secret in this Github repository to be able to continue publishing.  Looking forward to seeing where you take the project - I was never able to afford the time to take it to where I wanted to.

Fully unit tested will be awesome, nicely done.  In the future if you need a hand with anything on it feel free to reach out, always happy to help if I'm able :)

**Comment by TiBianMod** [comment]
Thank you very much again @Scotley, I will do my best.

I hope you doing well and if I need something I will contact you, (you can do the same and contact me if you need something)
