### ISSUE TITLE
breaks with vuex-orm 0.36.4 due to missing lib

### ISSUE THREAD

**Issue by aschempp** [Scotley/vuex-orm-decorators#17]
Similar to this issue: https://github.com/vuex-orm/vuex-orm/issues/724

vuex-orm 0.36.4 remove the /lib/ folder and only contains a dist. Some of the imports in this library do not work anymore. I tried to replace them with imports from `/dist/src/…` but had other issues (not sure if they were related).

**Comment by TiBianMod** [comment]
Thank you for the report @aschempp.

**Comment by aschempp** [comment]
Thank you for the quick fix!

Maybe you need to increase the minimum dependency? I think the dist files were not available in prior versions, but I'm not an expert in NPM stuff 🙃

**Comment by TiBianMod** [comment]
Already done on the next branch 🙂
