### ISSUE TITLE
TypeError: this.types is not a function

### ISSUE THREAD

**Issue by breynolds** [Scotley/vuex-orm-decorators#3]
When I try to insert into the DB, I get the error TypeError: **this.types is not a function**

Entity looks like this

```
import { Model } from "@vuex-orm/core";
import { NumberField, OrmModel, StringField } from "vuex-orm-decorators";

@OrmModel("races")
export default class Race extends Model {
  @NumberField()
  public ID!: number;

  @StringField()
  public Name!: string;
}
```
store looks like this:

```
import Vue from "vue";
import Vuex from "vuex";
import { ORMDatabase } from "vuex-orm-decorators";

Vue.use(Vuex);

export default new Vuex.Store({
  .
  .
  .
  plugins: [ORMDatabase.install()]
});
```
Also, maybe this is a clue.... in Vuex-Orm, this.setters is returning a value, but this.setters('all') is returning undefined.

```
/**
 * Get all records.
 */
Model.all = function () {
   return this.getters('all')();
};
```
From seeing the undefined basic fields and functions, it seems like the vuex-orm database isn't getting set up correctly. Any ideas?

I also posted this on StackOverflow to see if other people have ideas. 
https://stackoverflow.com/questions/59020879/typeerror-this-types-is-not-a-function-when-using-vuex-orm-decorators

**Comment by Scotley** [comment]
Hi,

I'm not to sure from first glance, it all looks like it should be working fine. I will have a dig around tomorrow and see what I can work out for you.  Potentially it is something that has changed in a newer version of vuex-orm.

I will get back to you.

**Comment by breynolds** [comment]
Ok, thanks for the info. If you need to, we can do a screen share.

**Comment by Scotley** [comment]
Can you share a some complete code which reproduces this issue please?

I need a bit more info on your issue. because I am struggling to reproduce it.

Edit: Reproduced your bug finally.  I will continue to investigate but it manifests differently in different vuex-orm versions.

**Comment by Scotley** [comment]
Can you please confirm something for me.

If you try this:

```typescript
store.dispatch('entities/races/insert', { data: { ID: 10, Name: 'Test' } })
console.log(Race.find(10));
```

Then you get the result that you expect and the race object is logged in the console.

but if you try:

```typescript
Race.insert({ ID: 10, Name: 'Test' });
```

then you get the error.

(If this is your error, I don't have a fix or an explanation as it seems to be an issue with vuex-orm itself).

Not sure why, and unfortunately I am no longer actively using it as I developed my own style orm store as I didn't need the complexity of vuex-orm, but needed more flexibility.  That is now my main focus :/

**Still, if I have missed the mark entirely, drop a complete example of your bug and I will look further into it.**

**Comment by breynolds** [comment]
I just tried directly calling the dispatch, and got the same thing. 

Don't worry about it. If you're not really going to actively use this code, I'll work out something else. Thanks for looking into it for me.

**Comment by Scotley** [comment]
No dramas mate, I will pass this on to @Kiaking anyway and he might be able to confirm whether there is an issue in the base library or not.

**Comment by kiaking** [comment]
Oh well that's because the argument is wrong. It should be;

```js
Race.insert({
  data: { ID: 10, Name: 'Test' } // <- You need `data` key.
});
```

**Comment by Scotley** [comment]
Aha, legend @kiaking. Thanks for that, I was missing the obvious for so long. @breynolds, is this solving your issue?  Perhaps you were making the same mistake as me?

**Comment by breynolds** [comment]
Yeah, I had already tried that. Same issue.
