### ISSUE TITLE
UID Type missing

### ISSUE THREAD

**Issue by sarim** [Scotley/vuex-orm-decorators#7]
```js
class User extends Model {
  static entity = 'users'

  static fields () {
    return {
      id: this.uid(() => uuid())
    }
  }
}
```

Seems like there is no `UidField` decorator?

**Comment by sarim** [comment]
After reading the source I see other decorators are ultimately calling the `Field(Model.....`. So tried that way.
```typescript
  @Field(Model.uid(() => uuid()))
```
this works. 
But obviously should have a `@UidField` decorator too.

**Comment by Scotley** [comment]
Yup, fair call. I must have missed that one. Merged, thanks for the input!

**Comment by sarim** [comment]
@Scotley I think the auto-publish to npm action isn't working bcz the version number haven't been increased in `package.json`. Can you check that please?

**Comment by Scotley** [comment]
Apologies, I have fixed the issue and npm is now on the correct version.
